[build]
  publish = "dist/app/browser"
  command = "npm run build:netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  # Las variables están configuradas en la interfaz de Netlify
  NODE_VERSION = "18.18.0" 